apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logql-proxy.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "logql-proxy.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "logql-proxy.configYaml" . | nindent 4 }}
